### ISSUE TITLE
The Examples and Hello World example applications fail to run

### ISSUE THREAD

**Issue by wbaldoumas** [wayfair-incubator/AeroSharp#157]
## Description

When I try to run the `Aerosharp.Examples` or `Aerosharp.HelloWorld` they fail to run. For example, the `Aerosharp.Examples` application fails with the following exception info:

```sh
AeroSharp.DataAccess.Exceptions.OperationFailedException
  HResult=0x80131500
  Message=Operation failed. Key keyName
  Source=AeroSharp
  StackTrace:
   at AeroSharp.DataAccess.Internal.RecordOperator.HandleAerospikeExceptions(AerospikeException ex, String key) in AeroSharp\src\AeroSharp\DataAccess\Internal\RecordOperator.cs:line 122
   at AeroSharp.DataAccess.Internal.RecordOperator.<DoOperation>d__10`1.MoveNext() in AeroSharp\src\AeroSharp\DataAccess\Internal\RecordOperator.cs:line 89
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at AeroSharp.Examples.Lists.ListIndexExample.<WriteToListAsync>d__4.MoveNext() in AeroSharp\examples\AeroSharp.Examples\Lists\ListIndexExample.cs:line 36
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at AeroSharp.Examples.Lists.ListIndexExample.<ExecuteAsync>d__3.MoveNext() in AeroSharp\examples\AeroSharp.Examples\Lists\ListIndexExample.cs:line 30
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at AeroSharp.Examples.Lists.ListExamples.<ExecuteAsync>d__2.MoveNext() in AeroSharp\examples\AeroSharp.Examples\Lists\ListExamples.cs:line 26
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at AeroSharp.Examples.App.<Run>d__0.MoveNext() in AeroSharp\examples\AeroSharp.Examples\App.cs:line 37
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at AeroSharp.Examples.Program.Main() in AeroSharp\examples\AeroSharp.Examples\Program.cs:line 7

  This exception was originally thrown at this call stack:
    [External Code]
    AeroSharp.DataAccess.Internal.RecordOperator.OperateAsync.AnonymousMethod__0(Aerospike.Client.IAsyncClient, Aerospike.Client.WritePolicy, Aerospike.Client.Key) in RecordOperator.cs
    AeroSharp.DataAccess.Internal.RecordOperator.DoOperation<T>(string, System.Func<Aerospike.Client.IAsyncClient, Aerospike.Client.WritePolicy, Aerospike.Client.Key, System.Threading.Tasks.Task<T>>, AeroSharp.DataAccess.WriteConfiguration) in RecordOperator.cs

Inner Exception 1:
InvalidNamespace: Error 20: Namespace not found in partition map: test_namespace
```

## Expected Behaviour

The examples and "hello world" apps run as expected without error.

## Actual Behaviour

The examples and "hello world" apps fail to run with the above exception.

## Steps to Reproduce

1. Run the `Aerosharp.Examples` or `Aerosharp.HelloWorld` apps locally
2. Observe the exception occur

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/wayfair-incubator/AeroSharp/blob/main/CONTRIBUTING.md)
- [x] I have verified this does not duplicate an existing issue

**Comment by wbaldoumas** [comment]
This has been addressed.
